"""add notices updated

Revision ID: 1d84780f5e7f
Revises: e34e8c8875bf
Create Date: 2026-06-22 20:39:09.765381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d84780f5e7f'
down_revision: Union[str, Sequence[str], None] = 'e34e8c8875bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('image_url', sa.String(), nullable=True))
    op.alter_column('notices', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('notices', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notices', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('notices', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('notices', 'image_url')
    # ### end Alembic commands ###
